version: '3.8'

services:
  app:
    image: java-translator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app  # For hot reload during development