data_final: false
data_korpus_nusantara: false
data_nusa_writes: true
data_nusax: false
enable_slang_replacement: true
k_fold_shuffle: true
k_fold_splits: 5
lowercase: true
max_sentence_length: 35
max_vocab_size: 30000
min_word_frequency: 2
min_word_length: 3
oov_token: <OOV>
padding_type: post
punctuation_to_remove: "[%.,?!\":;()[]\"-=@\xA9\xC3$\xA8*\u2030]"
random_state: 42
remove_diacritics: true
remove_emails: true
remove_html_tags: true
remove_punctuation: true
remove_quotes: true
remove_urls: true
slang_dictionaries:
- ../app/data/new_kamusalay.csv
- ../app/data/inforformal-formal-Indonesian-dictionary.tsv
- ../app/data/kamus_alay_versi2.csv
special_char_regex: '[^\w\s-]'
test_size: 0.2
tokenization_method: word_tokenize
unicode_normalization: true
