attention: true
batch_size: 64
epochs: 20
indo_vocab_size: 6780
java_vocab_size: 10460
latent_dim: 256
learning_rate: 0.001
loss: sparse_categorical_crossentropy
maxlength: 68
metrics:
  - accuracy
num_decoder_tokens: 10459
num_encoder_tokens: 6779
optimizer: AdamW
